name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/_build_wheels.yaml

  pypi:
    name: Upload wheels to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: pipx run build
      - run: pipx run twine upload dist/* --disable-progress-bar
        env:
          TWINE_USERNAME: '__token__'
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
